name: celk

services:
  redis:
    container_name: redis
    image: redis
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      # Using environment to add error handling for missing variables
      REDIS_PORT: ${REDIS_PORT:?'REDIS_PORT' variable is not set}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?'REDIS_PASSWORD' variable is not set}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      # Using environment to add error handling for missing variables
      POSTGRES_PORT: ${POSTGRES_PORT:?'POSTGRES_PORT' variable is not set}
      POSTGRES_USER: ${POSTGRES_USER:?'POSTGRES_USER' variable is not set}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?'POSTGRES_PASSWORD' variable is not set}
      POSTGRES_DB: ${POSTGRES_DB:?'POSTGRES_DB' variable is not set}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p ${POSTGRES_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3