name: celk-js
services:
  redis:
    image: redis
    restart: always
    env_file:
      - path: .env
        required: true
    environment:
      # Using environment to add error handling for missing variables
      REDIS_PORT: ${REDIS_PORT:?'REDIS_PORT' variable is not set}
      REDIS_PASSWORD: ${REDIS_PASSWORD:?'REDIS_PASSWORD' variable is not set}
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./env/docker/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3

