name: celk

services:
  redis:
    image: redis
    restart: always
    command:
      - /bin/sh
      - -c
      - redis-server
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 30s
      retries: 3
