import fs from "node:fs"
import path from "node:path"
import dedent from "dedent"

console.log("\x1b[34m ▷ \x1b[0mSyncing C++ header files to workers...")

const AUTOGENERATED_HEADER = dedent`
    // THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
    // @cybearl/celk-protocol
`

const cppDir = path.join(__dirname, "../src/cpp")
const workersDir = path.join(__dirname, "../../workers/src")

const files = ["address.hpp", "userOptions.hpp", "protocol.hpp"] as const

for (const file of files) {
    const srcPath = path.join(cppDir, file)
    const destPath = path.join(workersDir, file)

    const content = fs.readFileSync(srcPath, "utf-8")
    fs.writeFileSync(destPath, `${AUTOGENERATED_HEADER}\n\n${content}`)

    console.log(`\x1b[32m ✓ \x1b[0mSynced '${file}' to workers`)
}
