// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// @cybearl/celk-protocol

#pragma once

#include <nlohmann/json.hpp>

/**
 * Note: Should match `WorkerUserOptions` defined in `userOptions.ts`.
 */

/**
 * @brief The subset of user options passed to each worker via the start message.
 */
struct UserOptions {
    bool autoDisableZeroBalance;
    bool mixGenerators;
};

NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(UserOptions, autoDisableZeroBalance, mixGenerators)
