#include "address.hpp"
#include <cstdint>

/**
 * @brief Defines the interface for private key generation, implementations of this interface will
 * provide the logic to generate private keys, which will then be used for address derivation
 * and matching.
 */
struct IPrivateKeyGenerator {
    /**
     * @brief Produces the next private key and fills the passed 32-byte array with it.
     * @param privateKey The fixed 32-byte array to fill with the generated private key.
     * @return True unless the implemented generator has a fixed space that is exhausted.
     */
    virtual bool next(uint8_t privateKey[32]) = 0;

    /**
     * @brief Returns the `AddressPrivateKeyGenerator` type that corresponds to the implemented generator,
     * used for filtering addresses that can be generated by this generator.
     */
    virtual AddressPrivateKeyGenerator getType() const = 0;

    /**
     * @brief Virtual destructor to ensure proper cleanup of derived classes.
     */
    virtual ~IPrivateKeyGenerator() = default;
};
